### PR TITLE
Fix `SyntaxError: Unexpected end of JSON input` At Rest.ts:89

### PR DESCRIPTION
**Pull request by BTX-ON-YT**

### CODE REVIEW

**Comment by UnschooledGamer** [comment]
@BTX-ON-YT what if other rest methods return null just incase

**Comment by BTX-ON-YT** [comment]
> 

Good point ill have a look

**Comment by BTX-ON-YT** [comment]
@UnschooledGamer 

I have applied the same catch to all methods get, post. patch and delete

**Comment by UnschooledGamer** [comment]
@BTX-ON-YT 
> 
I had thought to use a function, That would be helpful incase Lavalink returns different type response in future
[image](https://imgur.com/a/dVHIW30)

**Comment by BTX-ON-YT** [comment]
@UnschooledGamer 

I will implement than into my pr

**Comment by parasop** [comment]
> @UnschooledGamer
> 
> I will implement than into my pr

Don't worry this will fix on v4.2

**Comment by BTX-ON-YT** [comment]
> @UnschooledGamer
> 
> I will implement than into my pr

Done

**Pull request closed without merging**
