### PR TITLE
feat: 🎸 Add support http search for lavalink

### PR DESCRIPTION
**Pull request by FabienBounoir**
I've added support for resolve with "http" links. Currently "http" links were not recognized as links and were therefore searched with source....

### CODE REVIEW

**Review by Joniii11 — APPROVED** [review]
Looks good to me,  let's wait for @UnschooledGamer to push this into the repo

**Comment by Joniii11** [comment]
Also edit it in `<Poru>.resolve` i overlooked that

**Comment by UnschooledGamer** [comment]
I'll look into it tomorrow

**Comment by UnschooledGamer** [comment]
Alright, Thanks for updating poru.resolve too.

**Pull request merged**
