### PR TITLE
Just better logs

### PR DESCRIPTION
**Pull request by Elitex07**

### CODE REVIEW

**Review by mitul009 — APPROVED** [review]

**Comment by Elitex07** [comment]
Damn

**Comment by UnschooledGamer** [comment]
It looks useless cause we can see the Error stack to refer to.

**Comment by Elitex07** [comment]
As the title says, "Just better logs". Nothing else ; )

**Comment by Elitex07** [comment]
merge when ?

**Comment by Elitex07** [comment]
@mitul009 merge when

**Comment by Elitex07** [comment]
🥲

**Pull request closed without merging**
